FROM node:14

WORKDIR /usr/src/app

# CHECKOUT BEN AWAD VIDEO ON THIS PLEASE...

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . .
COPY .env.production .env

RUN yarn build

ENV NODE_ENV production

# GONNA CHECK HOW TO START THIS TOO?
EXPOSE 8080
CMD [ "node", "dist/index.js" ]
USER node

# CMD ["npm", "start"]